name: Transmission
version: 0.7.2
slug: transmission
description: The torrent client for Hass.io with OpenVPN support
url: https://github.com/pierrickrouxel/hassio-addon-transmission
startup: services
ingress: true
panel_icon: mdi:progress-download
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
map:
- config:rw
- media:rw
- share:rw
- ssl
ports:
  9091/tcp: null
  51413/tcp: 51413
  51413/udp: 51413
ports_description:
  9091/tcp: Web UI port (Not required for Hass.io Ingress)
  51413/tcp: Peer port (setup port forwarding to this port)
  51413/udp: Peer port (setup port forwarding to this port)
privileged:
- NET_ADMIN
devices:
- /dev/net/tun
hassio_api: true
options:
  log_level: info
  authentication_required: false
  username: null
  password: null
  openvpn_enabled: false
  openvpn_config: null
  openvpn_username: null
  openvpn_password: null
  local_network: 192.168.1.0/24
schema:
  log_level: match(^(trace|debug|info|notice|warning|error|fatal)$)
  authentication_required: bool
  username: str
  password: str
  openvpn_enabled: bool
  openvpn_config: str
  openvpn_username: str
  openvpn_password: str
  local_network: str
environment:
  LOG_FORMAT: '{LEVEL}: {MESSAGE}'
init: false
image: ghcr.io/haberda/transmission/{arch}
