name: Signal Messenger
url: https://github.com/TheBlackMini/signal-addon/tree/master/
version: 0.67.1
slug: signal_messenger
arch:
- aarch64
- amd64
- armv7
description: Signal Messenger for Home Assistant
startup: system
boot: manual
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Rest-api port
options:
  mode: list(normal|native|json-rpc)
  AUTO_RECEIVE: true
  SIGNAL_CLI_CMD_TIMEOUT: 60
schema:
  mode: list(normal|native|json-rpc)
  AUTO_RECEIVE: bool
  SIGNAL_CLI_CMD_TIMEOUT: int
  reset_data: bool?
environment:
  SIGNAL_CLI_CONFIG_DIR: /data
image: ghcr.io/TheBlackMini/signal_messenger/{arch}
